services:
  pgdb:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /frontend
          ignore:
            - node_modules
  backend:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - pgdb
volumes:
  postgres_data: